const $ = (selector) => document.querySelector(selector);
if (![...document.styleSheets].some((sheet) => sheet.href && sheet.href.includes('styles.css'))) { const link = document.createElement('link'); link.rel = 'stylesheet'; link.href = 'https://raw.githubusercontent.com/adam2017abdo4-spec/adam-abdelsalam-portfolio/main/styles.css?v=3'; document.head.appendChild(link); }
$('#year').textContent = new Date().getFullYear();
const nav = document.querySelector('nav'); $('.menu-toggle').addEventListener('click', () => nav.classList.toggle('open'));
const accountButton = document.createElement('button'); accountButton.className = 'account-button'; accountButton.type = 'button'; accountButton.textContent = localStorage.getItem('adamAccount') || localStorage.getItem('adamGuest') ? 'My account' : 'Log in / Sign up'; nav.appendChild(accountButton);
const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); } }), { threshold: .12 }); document.querySelectorAll('.reveal').forEach((el) => observer.observe(el));
const projectForm = $('#project-form'); const savedProjects = () => { try { return JSON.parse(localStorage.getItem('adamProjects') || '[]'); } catch { return []; } }; const safe = (value) => { const el = document.createElement('div'); el.textContent = value; return el.innerHTML; }; function addProject(project) { const article = document.createElement('article'); article.innerHTML = `<div class="art dark">NEW / PROJECT<strong>✦</strong></div><div class="info"><small>PERSONAL WORK</small><h3>${safe(project.title)}</h3><p>${safe(project.description)}</p><em>${safe(project.tech || 'Project')}</em>${project.link ? `<a href="${project.link.replace(/["'<>]/g, '')}" target="_blank" rel="noopener">View project ↗</a>` : ''}</div>`; document.querySelector('.projects').append(article); } savedProjects().forEach(addProject);
projectForm.addEventListener('submit', (event) => { event.preventDefault(); const project = { title: $('#title').value.trim(), description: $('#description').value.trim(), link: $('#link').value.trim(), tech: $('#tech').value.trim() }; localStorage.setItem('adamProjects', JSON.stringify([...savedProjects(), project])); addProject(project); projectForm.reset(); projectForm.querySelector('output').textContent = 'Project added in this browser.'; });
$('#contact-form').addEventListener('submit', (event) => { event.preventDefault(); const name = $('#contact-name').value.trim(); const email = $('#contact-email').value.trim(); const body = encodeURIComponent(`${$('#contact-message').value.trim()}\n\nFrom: ${name} (${email})`); window.location.href = `mailto:adam2017abdo4@gmail.com?subject=${encodeURIComponent(`Portfolio message from ${name}`)}&body=${body}`; });
const modal = $('#auth-modal'); const authForm = $('#auth-form'); const authOutput = authForm.querySelector('output'); let authMode = 'login'; function setAuthMode(mode) { authMode = mode; document.querySelectorAll('.auth-tabs button').forEach((button) => button.classList.toggle('active', button.dataset.mode === mode)); $('#password-label').hidden = mode === 'signup'; $('#code-label').hidden = mode !== 'signup'; $('#auth-password').required = mode === 'login'; authOutput.textContent = mode === 'signup' ? 'Enter your email and password, then Continue to generate a demo code.' : ''; } function openAuth(mode = 'login') { modal.hidden = false; setAuthMode(mode); $('#auth-email').focus(); } accountButton.addEventListener('click', () => openAuth()); $('.close-auth').addEventListener('click', () => { modal.hidden = true; }); document.querySelectorAll('.auth-tabs button').forEach((button) => button.addEventListener('click', () => setAuthMode(button.dataset.mode))); $('#guest-button').addEventListener('click', () => { localStorage.setItem('adamGuest', 'true'); modal.hidden = true; accountButton.textContent = 'Guest mode'; });
authForm.addEventListener('submit', (event) => { event.preventDefault(); const email = $('#auth-email').value.trim().toLowerCase(); const password = $('#auth-password').value; const code = $('#auth-code').value.trim(); let accounts = {}; try { accounts = JSON.parse(localStorage.getItem('adamAccounts') || '{}'); } catch { accounts = {}; } if (authMode === 'signup') { if (!accounts[email]) { accounts[email] = { password, verificationCode: String(Math.floor(100000 + Math.random() * 900000)), verified: false }; localStorage.setItem('adamAccounts', JSON.stringify(accounts)); } if (!code) { authOutput.textContent = `Demo verification code: ${accounts[email].verificationCode}. Enter it above to finish signing up.`; return; } if (accounts[email].verificationCode !== code) { authOutput.textContent = 'The verification code is incorrect.'; return; } accounts[email].verified = true; localStorage.setItem('adamAccounts', JSON.stringify(accounts)); localStorage.setItem('adamAccount', email); accountButton.textContent = 'My account'; modal.hidden = true; return; } if (!accounts[email] || accounts[email].password !== password || !accounts[email].verified) { authOutput.textContent = 'Email, password, or verification status is incorrect.'; return; } localStorage.setItem('adamAccount', email); accountButton.textContent = 'My account'; modal.hidden = true; });
